import inquirer from 'inquirer';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

export async function decisionLog(title: string | undefined) {
  console.log('\n📋 Product-Mode Decision Log\n');
  
  let decisionTitle: string;
  
  if (title && title.trim().length > 0) {
    decisionTitle = title.trim();
  } else {
    const { titleInput } = await inquirer.prompt([
      {
        type: 'input',
        name: 'titleInput',
        message: 'Decision title:',
        validate: (input: string) => input.length > 0 || 'Please provide a title for the decision'
      }
    ]);
    decisionTitle = titleInput;
  }

  // decisionTitle is now definitely a non-empty string
  const questions = [
    {
      type: 'input',
      name: 'date',
      message: 'Date (YYYY-MM-DD):',
      default: new Date().toISOString().split('T')[0],
      validate: (input: string) => /^\d{4}-\d{2}-\d{2}$/.test(input) || 'Please use YYYY-MM-DD format'
    },
    {
      type: 'input',
      name: 'context',
      message: 'Context: [problem, constraints]',
      validate: (input: string) => input.length > 0 || 'Please provide context'
    },
    {
      type: 'input',
      name: 'options',
      message: 'Options considered: [A, B, C] (comma-separated)',
      validate: (input: string) => input.length > 0 || 'Please list options considered'
    },
    {
      type: 'input',
      name: 'choice',
      message: 'Choice: [X], because [reason]',
      validate: (input: string) => input.length > 0 || 'Please specify your choice and reason'
    },
    {
      type: 'list',
      name: 'reversibility',
      message: 'Reversibility:',
      choices: ['one-way door', 'two-way door'],
      default: 'two-way door'
    },
    {
      type: 'input',
      name: 'revisitTrigger',
      message: 'Revisit trigger: [metric / date / condition that reopens this]',
      validate: (input: string) => input.length > 0 || 'Please specify when this decision should be revisited'
    }
  ];

  try {
    const answers = await inquirer.prompt(questions);
    
    // Create timestamp for filename
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeTitle = decisionTitle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    
    const filename = `.product-mode/decisions/${timestamp}-${safeTitle}.md`;
    
    // Ensure directory exists
    const dir = join(process.cwd(), '.product-mode', 'decisions');
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    // Create decision log entry
    const content = `## Decision: ${decisionTitle}\nDate: ${answers.date}\nContext: ${answers.context}\nOptions considered: [${answers.options}]\nChoice: ${answers.choice}\nReversibility: ${answers.reversibility}\nRevisit trigger: ${answers.revisitTrigger}\n\n---\n*Generated by product-mode CLI*\n`;
    
    writeFileSync(join(process.cwd(), filename), content, 'utf8');
    
    console.log('\n✅ Decision logged!');
    console.log(`📝 Saved to: ./${filename}\n`);
    
  } catch (error) {
    if (error !== 'invalid') { // inquirer cancels with this
      console.error('❌ Error logging decision:', error);
    }
  }
}