import inquirer from 'inquirer';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

export async function preflightChecklist(workDescription?: string) {
  console.log('\n🚀 Product-Mode Pre-Flight Checklist\n');
  
  if (workDescription) {
    console.log(`Work: ${workDescription}\n`);
  }

  const questions = [
    {
      type: 'input',
      name: 'problem',
      message: 'Problem: Whose pain are we solving, in one sentence?',
      validate: (input: string) => input.length > 0 || 'Please describe the problem'
    },
    {
      type: 'input',
      name: 'whyNow',
      message: 'Why now: What changed? (evidence, trigger, cost of waiting)',
      validate: (input: string) => input.length > 0 || 'Please explain why this needs to be done now'
    },
    {
      type: 'input',
      name: 'scope',
      message: 'Scope: Smallest change that tests the hypothesis',
      validate: (input: string) => input.length > 0 || 'Please define the scope'
    },
    {
      type: 'input',
      name: 'successMetric',
      message: 'Success metric: The one number we expect to move',
      validate: (input: string) => input.length > 0 || 'Please define your success metric'
    },
    {
      type: 'input',
      name: 'reversibility',
      message: 'Reversibility: One-way or two-way door?',
      validate: (input: string) => input.length > 0 || 'Please specify if this is reversible'
    }
  ];

  try {
    const answers = await inquirer.prompt(questions);
    
    // Create timestamp for filename
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeDescription = (workDescription || 'work')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    
    const filename = `.product-mode/checklist/${timestamp}-${safeDescription}.md`;
    
    // Ensure directory exists
    const dir = join(process.cwd(), '.product-mode', 'checklist');
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    // Create checklist entry
    const content = `# Product-Mode Pre-Flight Checklist\n\n**Work:** ${workDescription || 'Unspecified work'}\n**Date:** ${new Date().toISOString().split('T')[0]}\n\n## Answers\n\n- **Problem**: ${answers.problem}\n- **Why now**: ${answers.whyNow}\n- **Scope**: ${answers.scope}\n- **Success metric**: ${answers.successMetric}\n- **Reversibility**: ${answers.reversibility}\n\n---\n*Generated by product-mode CLI*\n`;
    
    writeFileSync(join(process.cwd(), filename), content, 'utf8');
    
    console.log('\n✅ Checklist completed!');
    console.log(`📝 Saved to: ./${filename}\n`);
    console.log('Remember to refer back to this as you work.');
    
  } catch (error) {
    if (error !== 'invalid') { // inquirer cancels with this
      console.error('❌ Error running checklist:', error);
    }
  }
}